//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://portal.yabatech.edu.ng/", ConfigurationName="ServiceReference1.yctoutserviceSoap")]
    public interface yctoutserviceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/retschoolfee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> retschoolfeeAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/getpayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getpaymentsResponseGetpaymentsResult> getpaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/getbiodata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getbiodataResponseGetbiodataResult> getbiodataAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/getprogtype", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getprogtypeAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/flagappnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> flagappnumAsync(string appnum, string appuser, string userpass, string serviceheadid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/dodo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> dodoAsync(string t1, string t2, string t3, string t4, string t5, int t6, string t7, string tx, string ty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/admitprogramid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> admitprogramidAsync(string appuser, string userpass, string progid, int alid, string serviceheadid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/admitappnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task admitappnumAsync(string appuser, string userpass, string appnum, string serviceheadid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/Unflagappnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task UnflagappnumAsync(string appuser, string userpass, string appnum, string serviceheadid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/genmatric", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> genmatricAsync(string appnum, int progid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/ret_schoolfee_payment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> ret_schoolfee_paymentAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/ret_session_courses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ret_session_coursesResponseRet_session_coursesResult> ret_session_coursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/ret_regcourses_for_matric", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ret_regcourses_for_matricResponseRet_regcourses_for_matricResult> ret_regcourses_for_matricAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/get_image", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> get_imageAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/get_hostel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> get_hostelAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/erp_user_detail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> erp_user_detailAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/ret_uploaded_scores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ret_uploaded_scoresAsync(string coscode, int progid, int progtypeid, int asession, int semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/ret_Putme_score", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ret_Putme_scoreAsync(string appnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/ret_Putme_score_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> ret_Putme_score_2Async(string appnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/Chk_requirement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Chk_requirementResponseChk_requirementResult> Chk_requirementAsync(string olevel, string appnum, int deptid, string tx, string ty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/createbiodate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> createbiodateAsync(string appnum, string surname, string firstname, string othername, string deptid, int apptypeid, int sexid, string email, string phone, string tx, string ty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/Chk_requirement2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Chk_requirement2Async(string olevel, string appnum, int deptid, string tx, string ty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/clear_matricgenerated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> clear_matricgeneratedAsync(string prevmatric, string appnum, int ebportaprogid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/retrun_schedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> retrun_scheduleAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/retrun_semester_course", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.retrun_semester_courseResponseRetrun_semester_courseResult> retrun_semester_courseAsync(string matricno, string semesterid1, string sessionid1);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/retrun_co_course", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.retrun_co_courseResponseRetrun_co_courseResult> retrun_co_courseAsync(string matricno, string semesterid1, string sessionid1);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/retrun_stud_state", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> retrun_stud_stateAsync(string matricno, string semesterid1, string sessionid1);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/register_student", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> register_studentAsync(string matricno, int semesterid, int sessionid, int levelid, string courses);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/register_student2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> register_student2Async(string matricno, int semesterid, int sessionid, int levelid, string courses, int programmeid, int programmetypeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/dodo_transcript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> dodo_transcriptAsync(string t1, string t2, string t3, string t4, string t5, int t6, string t7, string tx, string ty, string cgpa, string tdestination);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/validate_erp_login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> validate_erp_loginAsync(string erpuser, string erp_password, string userid, string usertoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/get_candidate_exam_result_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.get_candidate_exam_result_detailsResponseGet_candidate_exam_result_detailsResult> get_candidate_exam_result_detailsAsync(string appnum, string user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/get_candidate_verificationstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> get_candidate_verificationstatusAsync(string appnum, string user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/chk_candidate_inverification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> chk_candidate_inverificationAsync(string appnum, string user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/get_candidate_paid_sitting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.get_candidate_paid_sittingResponseGet_candidate_paid_sittingResult> get_candidate_paid_sittingAsync(string appnum, string user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/check_candidate_paid_sitting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> check_candidate_paid_sittingAsync(string appnum, string user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/finalize_app_verification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> finalize_app_verificationAsync(string appnum, string user, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://portal.yabatech.edu.ng/chk_appnum_details_inverification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> chk_appnum_details_inverificationAsync(string appnum, string examnum, string examyear, string examname, string examtype, string user, string token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class getpaymentsResponseGetpaymentsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class getbiodataResponseGetbiodataResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class ret_session_coursesResponseRet_session_coursesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class ret_regcourses_for_matricResponseRet_regcourses_for_matricResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class Chk_requirementResponseChk_requirementResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class retrun_semester_courseResponseRetrun_semester_courseResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class retrun_co_courseResponseRetrun_co_courseResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class get_candidate_exam_result_detailsResponseGet_candidate_exam_result_detailsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://portal.yabatech.edu.ng/")]
    public partial class get_candidate_paid_sittingResponseGet_candidate_paid_sittingResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface yctoutserviceSoapChannel : ServiceReference1.yctoutserviceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class yctoutserviceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.yctoutserviceSoap>, ServiceReference1.yctoutserviceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public yctoutserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(yctoutserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), yctoutserviceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public yctoutserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(yctoutserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public yctoutserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(yctoutserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public yctoutserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public System.Threading.Tasks.Task<double> retschoolfeeAsync(string matricno)
        {
            return base.Channel.retschoolfeeAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getpaymentsResponseGetpaymentsResult> getpaymentsAsync()
        {
            return base.Channel.getpaymentsAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getbiodataResponseGetbiodataResult> getbiodataAsync(string matricno)
        {
            return base.Channel.getbiodataAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<string> getprogtypeAsync(string matricno)
        {
            return base.Channel.getprogtypeAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<int> flagappnumAsync(string appnum, string appuser, string userpass, string serviceheadid, string token)
        {
            return base.Channel.flagappnumAsync(appnum, appuser, userpass, serviceheadid, token);
        }
        
        public System.Threading.Tasks.Task<int> dodoAsync(string t1, string t2, string t3, string t4, string t5, int t6, string t7, string tx, string ty)
        {
            return base.Channel.dodoAsync(t1, t2, t3, t4, t5, t6, t7, tx, ty);
        }
        
        public System.Threading.Tasks.Task<int> admitprogramidAsync(string appuser, string userpass, string progid, int alid, string serviceheadid, string token)
        {
            return base.Channel.admitprogramidAsync(appuser, userpass, progid, alid, serviceheadid, token);
        }
        
        public System.Threading.Tasks.Task admitappnumAsync(string appuser, string userpass, string appnum, string serviceheadid, string token)
        {
            return base.Channel.admitappnumAsync(appuser, userpass, appnum, serviceheadid, token);
        }
        
        public System.Threading.Tasks.Task UnflagappnumAsync(string appuser, string userpass, string appnum, string serviceheadid, string token)
        {
            return base.Channel.UnflagappnumAsync(appuser, userpass, appnum, serviceheadid, token);
        }
        
        public System.Threading.Tasks.Task<int> genmatricAsync(string appnum, int progid)
        {
            return base.Channel.genmatricAsync(appnum, progid);
        }
        
        public System.Threading.Tasks.Task<double> ret_schoolfee_paymentAsync(string matricno)
        {
            return base.Channel.ret_schoolfee_paymentAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ret_session_coursesResponseRet_session_coursesResult> ret_session_coursesAsync()
        {
            return base.Channel.ret_session_coursesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ret_regcourses_for_matricResponseRet_regcourses_for_matricResult> ret_regcourses_for_matricAsync(string matricno)
        {
            return base.Channel.ret_regcourses_for_matricAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<string> get_imageAsync(string matricno)
        {
            return base.Channel.get_imageAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<string> get_hostelAsync(string matricno)
        {
            return base.Channel.get_hostelAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<string> erp_user_detailAsync(int userid)
        {
            return base.Channel.erp_user_detailAsync(userid);
        }
        
        public System.Threading.Tasks.Task<int> ret_uploaded_scoresAsync(string coscode, int progid, int progtypeid, int asession, int semester)
        {
            return base.Channel.ret_uploaded_scoresAsync(coscode, progid, progtypeid, asession, semester);
        }
        
        public System.Threading.Tasks.Task<string> ret_Putme_scoreAsync(string appnum)
        {
            return base.Channel.ret_Putme_scoreAsync(appnum);
        }
        
        public System.Threading.Tasks.Task<double> ret_Putme_score_2Async(string appnum)
        {
            return base.Channel.ret_Putme_score_2Async(appnum);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Chk_requirementResponseChk_requirementResult> Chk_requirementAsync(string olevel, string appnum, int deptid, string tx, string ty)
        {
            return base.Channel.Chk_requirementAsync(olevel, appnum, deptid, tx, ty);
        }
        
        public System.Threading.Tasks.Task<int> createbiodateAsync(string appnum, string surname, string firstname, string othername, string deptid, int apptypeid, int sexid, string email, string phone, string tx, string ty)
        {
            return base.Channel.createbiodateAsync(appnum, surname, firstname, othername, deptid, apptypeid, sexid, email, phone, tx, ty);
        }
        
        public System.Threading.Tasks.Task<string> Chk_requirement2Async(string olevel, string appnum, int deptid, string tx, string ty)
        {
            return base.Channel.Chk_requirement2Async(olevel, appnum, deptid, tx, ty);
        }
        
        public System.Threading.Tasks.Task<int> clear_matricgeneratedAsync(string prevmatric, string appnum, int ebportaprogid)
        {
            return base.Channel.clear_matricgeneratedAsync(prevmatric, appnum, ebportaprogid);
        }
        
        public System.Threading.Tasks.Task<string> retrun_scheduleAsync(string matricno)
        {
            return base.Channel.retrun_scheduleAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.retrun_semester_courseResponseRetrun_semester_courseResult> retrun_semester_courseAsync(string matricno, string semesterid1, string sessionid1)
        {
            return base.Channel.retrun_semester_courseAsync(matricno, semesterid1, sessionid1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.retrun_co_courseResponseRetrun_co_courseResult> retrun_co_courseAsync(string matricno, string semesterid1, string sessionid1)
        {
            return base.Channel.retrun_co_courseAsync(matricno, semesterid1, sessionid1);
        }
        
        public System.Threading.Tasks.Task<int> retrun_stud_stateAsync(string matricno, string semesterid1, string sessionid1)
        {
            return base.Channel.retrun_stud_stateAsync(matricno, semesterid1, sessionid1);
        }
        
        public System.Threading.Tasks.Task<int> register_studentAsync(string matricno, int semesterid, int sessionid, int levelid, string courses)
        {
            return base.Channel.register_studentAsync(matricno, semesterid, sessionid, levelid, courses);
        }
        
        public System.Threading.Tasks.Task<int> register_student2Async(string matricno, int semesterid, int sessionid, int levelid, string courses, int programmeid, int programmetypeid)
        {
            return base.Channel.register_student2Async(matricno, semesterid, sessionid, levelid, courses, programmeid, programmetypeid);
        }
        
        public System.Threading.Tasks.Task<int> dodo_transcriptAsync(string t1, string t2, string t3, string t4, string t5, int t6, string t7, string tx, string ty, string cgpa, string tdestination)
        {
            return base.Channel.dodo_transcriptAsync(t1, t2, t3, t4, t5, t6, t7, tx, ty, cgpa, tdestination);
        }
        
        public System.Threading.Tasks.Task<int> validate_erp_loginAsync(string erpuser, string erp_password, string userid, string usertoken)
        {
            return base.Channel.validate_erp_loginAsync(erpuser, erp_password, userid, usertoken);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.get_candidate_exam_result_detailsResponseGet_candidate_exam_result_detailsResult> get_candidate_exam_result_detailsAsync(string appnum, string user, string token)
        {
            return base.Channel.get_candidate_exam_result_detailsAsync(appnum, user, token);
        }
        
        public System.Threading.Tasks.Task<int> get_candidate_verificationstatusAsync(string appnum, string user, string token)
        {
            return base.Channel.get_candidate_verificationstatusAsync(appnum, user, token);
        }
        
        public System.Threading.Tasks.Task<int> chk_candidate_inverificationAsync(string appnum, string user, string token)
        {
            return base.Channel.chk_candidate_inverificationAsync(appnum, user, token);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.get_candidate_paid_sittingResponseGet_candidate_paid_sittingResult> get_candidate_paid_sittingAsync(string appnum, string user, string token)
        {
            return base.Channel.get_candidate_paid_sittingAsync(appnum, user, token);
        }
        
        public System.Threading.Tasks.Task<int> check_candidate_paid_sittingAsync(string appnum, string user, string token)
        {
            return base.Channel.check_candidate_paid_sittingAsync(appnum, user, token);
        }
        
        public System.Threading.Tasks.Task<int> finalize_app_verificationAsync(string appnum, string user, string token)
        {
            return base.Channel.finalize_app_verificationAsync(appnum, user, token);
        }
        
        public System.Threading.Tasks.Task<int> chk_appnum_details_inverificationAsync(string appnum, string examnum, string examyear, string examname, string examtype, string user, string token)
        {
            return base.Channel.chk_appnum_details_inverificationAsync(appnum, examnum, examyear, examname, examtype, user, token);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.yabatech.edu.ng/paymentservice/yctoutservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.yabatech.edu.ng/paymentservice/yctoutservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            yctoutserviceSoap,
            
            yctoutserviceSoap12,
        }
    }
}
